version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "s3://s3-jan-22/TEST/"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - pwd
        - rm -Rf node_modules
        - rm -f package-lock.json
        #- npm install --package-lock-only
        - npm install -g @angular/cli
        - npm install
        - npm install --save-dev webpack
  build:
    commands:
        - echo Build started 
        - pwd
        - ls -a
        #- ng build --prod
        - ng build ----configuration production
        - ls -a
  post_build:
     commands:
      - aws s3 cp dist s3://s3-jan-22/TEST/ --recursive
      - echo Files pushed to S3 Bucket
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
  